-- https://school.programmers.co.kr/learn/courses/30/lessons/276034
-- 조건에 맞는 개발자 찾기

-- 코드를 작성해주세요
SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS AS D
WHERE D.SKILL_CODE & (SELECT SKILLCODES.CODE FROM SKILLCODES WHERE NAME = 'Python') > 0 OR D.SKILL_CODE & (SELECT SKILLCODES.CODE FROM SKILLCODES WHERE NAME = 'C#')> 0
ORDER BY D.ID ASC

