--https://school.programmers.co.kr/learn/courses/30/lessons/164673

SELECT u.TITLE, u.BOARD_ID, d.REPLY_ID, d.WRITER_ID, d.CONTENTS, DATE_FORMAT(d.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS u
JOIN USED_GOODS_REPLY AS d ON u.BOARD_ID = d.BOARD_ID
WHERE DATE_FORMAT(u.CREATED_DATE, '%Y-%m-%d') BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY CREATED_DATE ASC, u.TITLE ASC;